---
server:
  port: 8383
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luccamac/microservices-spring-cloud
          search-paths:
               - 'station*'
          repos:
            perf:
              pattern: '*/perf'
              uri: https://github.com/luccamac/microservices-spring-cloud-performance
              search-paths: 'station*'
      enabled: false